name = "uxnknwn/jecs_util"
version = "0.1.0-alpha.3"
description = "Reusable utilities for Jecs 0.11 and Roblox ECS projects"
authors = ["Dale Harris IV"]
repository = "https://github.com/uxnknwn/jecs-util"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dependencies]
jecs = { wally = "ukendio/jecs", version = "=0.11.0" }

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.6.1", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.5.0", target = "lune" }
selene = { name = "pesde/selene", version = "^0.31.0", target = "lune" }

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"
